-- 33 · Registro de errores de la tienda para el panel Salud del POS
-- =================================================================
-- Gemela de sevelin-pos-oficial/sql/48-registro-errores.sql.
--
-- Los errores del servidor de sevelin.cl (webhooks de pago, correos que no
-- salen, el POS que no responde, catálogo que no carga…) solo vivían en los
-- logs de Vercel, que se borran en una hora. Ahora se guardan acá y el POS
-- los muestra en Página Web → Salud, agrupados.
--
-- Cada app escribe en SU base a propósito: si esta base se cae, el POS
-- igual registra lo suyo, y viceversa.
--
-- Nunca se guardan llaves ni tokens (se enmascaran antes). Se conserva 30 días.
--
-- Idempotente.

create table if not exists registro_errores (
  id          bigint generated by default as identity primary key,
  creado_en   timestamptz not null default now(),
  origen      text not null,              -- 'TIENDA'
  ruta        text null,
  metodo      text null,
  estado_http integer null,
  mensaje     text not null,
  detalle     text null
);

create index if not exists idx_registro_errores_creado on registro_errores (creado_en desc);

-- Solo el servidor (service_role) entra: la anon key pública no lee ni escribe.
alter table registro_errores enable row level security;

comment on table registro_errores is
  'Errores del servidor de la tienda, para el panel Salud del POS. Sin secretos. Se conserva 30 días.';
