-- 35 · Cotizaciones que el cliente se hace solo
-- =============================================
-- POR QUÉ (dueño, 17-09-2026)
-- "Que el que selecciona sus productos, aparte de poder comprarlos, pueda
--  cotizar todos esos productos y hacerlos en documento, para que las
--  empresas o clientes hagan su cotización ellos mismos."
--
-- Hoy una empresa que quiere cotizar tiene que escribir por WhatsApp y
-- esperar. Con esto arma el carrito, aprieta un botón y se lleva el
-- documento — y el dueño se entera de qué le están cotizando, por cuánto
-- y quién, que es información de venta que hoy se pierde entera.
--
-- UNA COTIZACIÓN ES UN DOCUMENTO, NO UNA CONSULTA
-- Por eso los montos se CONGELAN acá (neto, iva, total y cada línea en
-- `items`) en vez de recalcularse contra el catálogo al abrirla. Si mañana
-- sube el precio de un monitor, el papel que el cliente tiene en la mano
-- debe seguir diciendo lo mismo que decía el día que se emitió. Recalcular
-- convertiría el documento en algo que cambia solo, y eso no es una
-- cotización.
--
-- NO RESERVA STOCK, y la página lo dice con todas sus letras: cotizar no
-- es comprar. Prometer unidades que otro cliente puede llevarse mientras
-- tanto sería peor que no cotizar.
--
-- VIGENCIA: hasta el final del día en que se emite (hora de Chile), como
-- lo pidió el dueño. El plazo vive en una constante del código
-- (DIAS_VALIDEZ_COTIZACION en src/lib/cotizaciones.ts), no acá: cambiarlo
-- no puede obligar a una migración.
--
-- Idempotente.

-- ---------- 1. Correlativo atómico ----------
-- Mismo criterio que generar_numero_pedido() (migración 02): contar filas
-- desde la app dejaría que dos cotizaciones simultáneas saquen el mismo
-- número y choquen contra el UNIQUE. nextval() es atómico.
create sequence if not exists cotizaciones_web_numero_seq start 1;

create or replace function generar_numero_cotizacion()
returns text as $$
begin
  return 'COT-' || lpad(nextval('cotizaciones_web_numero_seq')::text, 6, '0');
end;
$$ language plpgsql;

-- ---------- 2. La tabla ----------
create table if not exists cotizaciones_web (
  id                  bigint generated by default as identity primary key,
  numero_cotizacion   text not null unique default generar_numero_cotizacion(),

  -- La URL pública no puede ser adivinable: el correlativo sí lo es, y una
  -- cotización lleva nombre, RUT y correo de una empresa. Mismo mecanismo
  -- y misma razón que pedidos_web.token_publico (migración 26): 32 hex =
  -- 128 bits, y conocer un token no da ninguna pista sobre los demás.
  token_publico       text not null unique default replace(gen_random_uuid()::text, '-', ''),

  creado_en           timestamptz not null default now(),
  vence_en            timestamptz not null,

  -- ---------- Quién cotiza ----------
  nombre              text not null,
  correo              text not null,
  telefono            text null,
  -- Datos de empresa: opcionales, porque también cotiza gente natural.
  empresa             text null,
  rut                 text null,
  giro                text null,
  nota                text null,

  -- Si estaba con sesión iniciada, queda amarrada a su cuenta para poder
  -- mostrársela en "Mis pedidos" más adelante. Nunca viene del body: se lee
  -- de la cookie en el servidor (mismo criterio que el checkout).
  cliente_user_id     uuid null,

  -- ---------- Montos congelados ----------
  -- Los tres se guardan aunque dos se puedan derivar del tercero: el
  -- documento tiene que poder reimprimirse idéntico sin depender de que la
  -- tasa de IVA o el redondeo de hoy sigan siendo los de entonces.
  neto                numeric not null check (neto >= 0),
  iva                 numeric not null check (iva >= 0),
  total               numeric not null check (total >= 0),
  -- [{ sku, nombre, cantidad, precio_unitario, neto_unitario, subtotal }]
  items               jsonb not null,

  -- Lo marca el dueño desde el POS cuando ya la gestionó, para que la lista
  -- de pendientes no crezca para siempre.
  gestionada_en       timestamptz null
);

create index if not exists cotizaciones_web_creado_idx on cotizaciones_web (creado_en desc);
create index if not exists cotizaciones_web_pendientes_idx
  on cotizaciones_web (creado_en desc) where gestionada_en is null;
create index if not exists cotizaciones_web_cliente_idx
  on cotizaciones_web (cliente_user_id) where cliente_user_id is not null;

-- ---------- 3. RLS ----------
-- Activada SIN políticas públicas: solo la service_role (server-only) la
-- toca. Sin esto la tabla queda abierta a la anon key, que sí viaja al
-- navegador — el mismo olvido que ya costó dos alertas críticas de
-- Supabase en este proyecto (avisos_producto, migración 34).
alter table cotizaciones_web enable row level security;

comment on table cotizaciones_web is
  'Cotizaciones que el cliente se genera solo desde el carrito. Los montos van CONGELADOS: el documento no puede cambiar después de emitido. No reserva stock (migración 35).';
comment on column cotizaciones_web.vence_en is
  'Fin de la vigencia. Por defecto, el final del día de emisión en hora de Chile. El plazo lo define DIAS_VALIDEZ_COTIZACION en src/lib/cotizaciones.ts.';
comment on column cotizaciones_web.items is
  'Las líneas tal como se emitieron, con su precio de ese día. No se recalculan nunca contra el catálogo.';
